version: "3.8"
services:
    nginx:
        container_name: ${PROJECT_NAME}_nginx
        build:
            context: ./docker/nginx
        ports:
            - "80:80"
            - "443:443"
        working_dir: /app
        depends_on:
            - php
        volumes:
            - ./:/app
    php:
        container_name: ${PROJECT_NAME}_php
        build:
            context: ./docker/php
        ports:
            - "9000:9000"
        working_dir: /app
        volumes:
            - ./:/app
    redis:
        container_name: ${PROJECT_NAME}_redis
        image: redis:7.0.2-alpine
