parameters:
    redis_dsn: '%env(resolve:REDIS_DSN)%'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\TelegramBotBundle\:
        resource: '../src/App/TelegramBotBundle/*'

    App\TelegramBotBundle\Factory\RedisClientFactory:
        arguments:
            - '%redis_dsn%'

    App\TelegramBotBundle\Factory\TelegramBotFactory:
        arguments:
            - '%telegram_bot.censorship.bot_username%'
            - '%telegram_bot.censorship.bot_api_key%'

    Longman\TelegramBot\Telegram:
        factory: ['@App\TelegramBotBundle\Factory\TelegramBotFactory', 'createTelegramBot']
        arguments: ['@monolog.logger.censorship_bot']

    App\TelegramBotBundle\Command\SetWebhookCommand:
        tags: ['console.command']
